version: '3'
services:
  lpic-test:
    image: dockette/docker-alpine-lpic
    container_name: lpic-test
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: /bin/sh -c "apk add --no-cache iproute2 iputils curl wget netcat-openbsd && /bin/sh"
